# Generated by Django 4.1.1 on 2022-09-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=12, unique=True, verbose_name='SKU')),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=20, verbose_name='Document')),
                ('ult_precio_compra', models.CharField(max_length=20)),
                ('marca', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SocioNegocios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=80, verbose_name='Razon Social')),
                ('nombre_fantasia', models.CharField(max_length=80, verbose_name='Nombre de Fantasia')),
                ('direccion', models.CharField(max_length=240, verbose_name='Direccion')),
                ('tipo_sn', models.CharField(max_length=1, verbose_name='Tipo de SN')),
                ('tipo_doc_fiscal', models.CharField(max_length=4, verbose_name='Tipo de Doc. fiscal')),
                ('doc_fiscal', models.BigIntegerField(unique=True)),
                ('telefono1', models.IntegerField()),
                ('telefono2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CodProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prov', models.CharField(max_length=20, verbose_name='Codigo de Proveedor')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgcrestapi.articulos')),
                ('socio_negocios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgcrestapi.socionegocios')),
            ],
        ),
    ]
