# Generated by Django 4.1.1 on 2022-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgcrestapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='marca',
            field=models.CharField(max_length=20, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='ult_precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
