# Generated by Django 4.1.1 on 2022-09-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgcrestapi', '0002_alter_articulos_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socionegocios',
            name='telefono2',
            field=models.IntegerField(null=True),
        ),
    ]
