# Generated by Django 4.1.1 on 2022-09-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgcrestapi', '0003_alter_socionegocios_telefono2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentrodeCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('socio_negocios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgcrestapi.socionegocios')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoInicialCDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_cotizado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgcrestapi.articulos')),
                ('cdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgcrestapi.centrodecosto')),
            ],
        ),
    ]
