# Generated by Django 4.1.1 on 2022-09-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgcrestapi', '0004_centrodecosto_saldoinicialcdc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_contabilizacion', models.DateField()),
                ('creador', models.CharField(max_length=20, verbose_name='Creador')),
                ('comentario', models.CharField(max_length=256, verbose_name='Comentario')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
                ('folio', models.CharField(max_length=15, verbose_name='Numero de Folio')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgcrestapi.centrodecosto')),
            ],
        ),
        migrations.CreateModel(
            name='LineasFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_linea', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=3, verbose_name='Moneda')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sgcrestapi.articulos')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgcrestapi.cabecerafactura')),
            ],
        ),
    ]
