# Generated by Django 4.1.1 on 2022-09-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgcrestapi', '0005_cabecerafactura_lineasfactura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineasfactura',
            old_name='iva',
            new_name='impuestos',
        ),
    ]
