# Generated by Django 4.1.1 on 2022-10-20 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgcrestapi', '0006_rename_iva_lineasfactura_impuestos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabecerafactura',
            name='sn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='sgcrestapi.socionegocios'),
            preserve_default=False,
        ),
    ]
